{% set name = "wagtail-nav-menus" %}
{% set version = "3.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail_nav_menus-{{ version }}.tar.gz
  sha256: 3154f3814dc3fd5af284b0d5490be31163ae463617e0f8237b36f73c405f5313

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.9.1
  run:
    - python >={{ python_min }},<4.0
    - wagtail >=5.2,<6.4
    - wagtail-modeladmin >=2.1.0,<3.0.0

test:
  imports:
    - wagtail_nav_menus
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/thelabnyc/wagtail-nav-menus
  summary: Wagtail Nav Menus is a app to provide highly customizable menus in wagtail by leveraging StreamFields.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
