{% set name = "wagtail-nav-menus" %}
{% set version = "3.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail-nav-menus-{{ version }}.tar.gz
  sha256: ee204d8ae9a9f78c64fe447a58da7328baf2ec1b905cd822f519e73b5b123692

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - versiontag
    - pip
  run:
    - python >=3.8
    - wagtail >=4.1,<6.0

test:
  imports:
    - wagtail_nav_menus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/thelabnyc/wagtail-nav-menus
  summary: Wagtail Nav Menus is a app to provide highly customizable menus in wagtail by leveraging StreamFields.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
