{% set name = "wagtail-nav-menus" %}
{% set version = "3.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e68dfef523d9ac7a42a6e3d2910e722ffd659582ba93f755f94bc29a53e450ba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - versiontag
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.8
    - wagtail >=4.1,<6.0

test:
  imports:
    - wagtail_nav_menus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/thelabnyc/wagtail-nav-menus
  summary: Wagtail Nav Menus is a app to provide highly customizable menus in wagtail by leveraging StreamFields.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
